//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Chess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_TW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_TW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Chess.zh_TW", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帥.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 風雲棋卦.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秋.
        /// </summary>
        internal static string autumn {
            get {
                return ResourceManager.GetString("autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大貴人.
        /// </summary>
        internal static string Benefactor1 {
            get {
                return ResourceManager.GetString("Benefactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵人.
        /// </summary>
        internal static string Benefactor10 {
            get {
                return ResourceManager.GetString("Benefactor10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好人.
        /// </summary>
        internal static string Benefactor11 {
            get {
                return ResourceManager.GetString("Benefactor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好人.
        /// </summary>
        internal static string Benefactor12 {
            get {
                return ResourceManager.GetString("Benefactor12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小人.
        /// </summary>
        internal static string Benefactor13 {
            get {
                return ResourceManager.GetString("Benefactor13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小人.
        /// </summary>
        internal static string Benefactor14 {
            get {
                return ResourceManager.GetString("Benefactor14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大貴人.
        /// </summary>
        internal static string Benefactor2 {
            get {
                return ResourceManager.GetString("Benefactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大貴人.
        /// </summary>
        internal static string Benefactor3 {
            get {
                return ResourceManager.GetString("Benefactor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中貴人.
        /// </summary>
        internal static string Benefactor4 {
            get {
                return ResourceManager.GetString("Benefactor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中貴人.
        /// </summary>
        internal static string Benefactor5 {
            get {
                return ResourceManager.GetString("Benefactor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小貴人.
        /// </summary>
        internal static string Benefactor6 {
            get {
                return ResourceManager.GetString("Benefactor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小貴人.
        /// </summary>
        internal static string Benefactor7 {
            get {
                return ResourceManager.GetString("Benefactor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵人.
        /// </summary>
        internal static string Benefactor8 {
            get {
                return ResourceManager.GetString("Benefactor8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵人.
        /// </summary>
        internal static string Benefactor9 {
            get {
                return ResourceManager.GetString("Benefactor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意見/問題內容.
        /// </summary>
        internal static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 俥.
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 傌.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東.
        /// </summary>
        internal static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵件.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地利.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前及未來很長時間才有機會可能發生.
        /// </summary>
        internal static string Event0_0_0 {
            get {
                return ResourceManager.GetString("Event0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待49天後，才會有可能產生機會.
        /// </summary>
        internal static string Event0_0_1 {
            get {
                return ResourceManager.GetString("Event0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要等待49天後才會有可能發生.
        /// </summary>
        internal static string Event0_1_0 {
            get {
                return ResourceManager.GetString("Event0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很久就已經存在的事實.
        /// </summary>
        internal static string Event0_1_1 {
            get {
                return ResourceManager.GetString("Event0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前及未來很長時間才有機會可能發生.
        /// </summary>
        internal static string Event1_0_0 {
            get {
                return ResourceManager.GetString("Event1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49天內將有凸顯事件.
        /// </summary>
        internal static string Event1_0_1 {
            get {
                return ResourceManager.GetString("Event1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要在等待49天後，才會有可能產生機會.
        /// </summary>
        internal static string Event1_1_0 {
            get {
                return ResourceManager.GetString("Event1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很早已經是存在的事實.
        /// </summary>
        internal static string Event1_1_1 {
            get {
                return ResourceManager.GetString("Event1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 炮.
        /// </summary>
        internal static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我要卜棋卦.
        /// </summary>
        internal static string Fortune {
            get {
                return ResourceManager.GetString("Fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問題.
        /// </summary>
        internal static string FortuneSub1 {
            get {
                return ResourceManager.GetString("FortuneSub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占卜答覆.
        /// </summary>
        internal static string FortuneSub2 {
            get {
                return ResourceManager.GetString("FortuneSub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件表現.
        /// </summary>
        internal static string FortuneSub3 {
            get {
                return ResourceManager.GetString("FortuneSub3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時空人為.
        /// </summary>
        internal static string FortuneSub4 {
            get {
                return ResourceManager.GetString("FortuneSub4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四季吉凶.
        /// </summary>
        internal static string FortuneSub5 {
            get {
                return ResourceManager.GetString("FortuneSub5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四方貴人.
        /// </summary>
        internal static string FortuneSub6 {
            get {
                return ResourceManager.GetString("FortuneSub6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 棋卦內涵.
        /// </summary>
        internal static string FortuneSub7 {
            get {
                return ResourceManager.GetString("FortuneSub7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本卦建言.
        /// </summary>
        internal static string FortuneSub8 {
            get {
                return ResourceManager.GetString("FortuneSub8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉轉凶.
        /// </summary>
        internal static string FortuneType1 {
            get {
                return ResourceManager.GetString("FortuneType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶.
        /// </summary>
        internal static string FortuneType10 {
            get {
                return ResourceManager.GetString("FortuneType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中凶.
        /// </summary>
        internal static string FortuneType11 {
            get {
                return ResourceManager.GetString("FortuneType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中凶.
        /// </summary>
        internal static string FortuneType12 {
            get {
                return ResourceManager.GetString("FortuneType12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小凶.
        /// </summary>
        internal static string FortuneType13 {
            get {
                return ResourceManager.GetString("FortuneType13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小凶.
        /// </summary>
        internal static string FortuneType14 {
            get {
                return ResourceManager.GetString("FortuneType14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉.
        /// </summary>
        internal static string FortuneType2 {
            get {
                return ResourceManager.GetString("FortuneType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉.
        /// </summary>
        internal static string FortuneType3 {
            get {
                return ResourceManager.GetString("FortuneType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中吉.
        /// </summary>
        internal static string FortuneType4 {
            get {
                return ResourceManager.GetString("FortuneType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中吉.
        /// </summary>
        internal static string FortuneType5 {
            get {
                return ResourceManager.GetString("FortuneType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小吉.
        /// </summary>
        internal static string FortuneType6 {
            get {
                return ResourceManager.GetString("FortuneType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小吉.
        /// </summary>
        internal static string FortuneType7 {
            get {
                return ResourceManager.GetString("FortuneType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶轉吉.
        /// </summary>
        internal static string FortuneType8 {
            get {
                return ResourceManager.GetString("FortuneType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶.
        /// </summary>
        internal static string FortuneType9 {
            get {
                return ResourceManager.GetString("FortuneType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兵.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋占卜沿革.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋是諸葛亮(孔明)利用中國易經的思想及結構理論所創造出來的，當初主要是利用簡單的木材，製做出推演戰略用的沙盤佈陣工具，後來孔明利用易經的一元兩儀五行思想創造出現代我們所使用的象棋，當時象棋還有另外一項功能，就是用在問卜戰事的吉兇，所以象棋透過一元領導的兩儀管事五行的結構，產生了正派及反派兩個勢力的謀略運用(稱為陰陽消長)，左右兩組仕相車馬炮為輔弼(稱為兩儀)，再配合東營南營北營西營中壇等五營兵隨令戰鬥(稱為五行)，所以全盤32顆棋子是配合中國的三合四象思想所創造出來的，象棋的其中一項功能就是占卜。.
        /// </summary>
        internal static string HistoryContent1 {
            get {
                return ResourceManager.GetString("HistoryContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋占卜所得到的解答是準確且直接的，所以占卜者要明白一件事，占卜所提出的問題尋求答案，必須是&quot;吉&quot;或&quot;兇&quot;的兩極回答，所以占卜不是算命而是問事，例如：問婚姻(江小明家住台北市松山區新東街3巷4號目前與王碧雲小姐認識交往三年【會不會】結婚)，默想三次後將棋隨機放入三角格陣中，就可以完成占卜過程，棋卦將會從三角格陣中的排列組合，運算出所問事件的&quot;會&quot;還是&quot;不會&quot;結婚，也可以從組合中得知事件的基礎、時機、環境、人為等相關的互動狀況，所以占卜首重有事才占，無事不占的原則，占卜時靜性心明默想排棋則會奇準無比。.
        /// </summary>
        internal static string HistoryContent2 {
            get {
                return ResourceManager.GetString("HistoryContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 士.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象.
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 車.
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 馬.
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卒.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北.
        /// </summary>
        internal static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (一個問題只能問一次,卜卦的結果才準確喔..).
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請心中默念您想問的事情及或相關人姓名或目的後，請按&quot;抄兵佈棋&quot;.
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請將32顆棋子中，任意點選6顆棋子.
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天時.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請摘要寫下您的問題.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吉凶.
        /// </summary>
        internal static string R1_1 {
            get {
                return ResourceManager.GetString("R1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凶.
        /// </summary>
        internal static string R1_1N {
            get {
                return ResourceManager.GetString("R1_1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吉.
        /// </summary>
        internal static string R1_1Y {
            get {
                return ResourceManager.GetString("R1_1Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有沒有.
        /// </summary>
        internal static string R1_2 {
            get {
                return ResourceManager.GetString("R1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒有.
        /// </summary>
        internal static string R1_2N {
            get {
                return ResourceManager.GetString("R1_2N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有.
        /// </summary>
        internal static string R1_2Y {
            get {
                return ResourceManager.GetString("R1_2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可不可.
        /// </summary>
        internal static string R1_3 {
            get {
                return ResourceManager.GetString("R1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可以.
        /// </summary>
        internal static string R1_3N {
            get {
                return ResourceManager.GetString("R1_3N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以.
        /// </summary>
        internal static string R1_3Y {
            get {
                return ResourceManager.GetString("R1_3Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會不會.
        /// </summary>
        internal static string R1_4 {
            get {
                return ResourceManager.GetString("R1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不會.
        /// </summary>
        internal static string R1_4N {
            get {
                return ResourceManager.GetString("R1_4N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會.
        /// </summary>
        internal static string R1_4Y {
            get {
                return ResourceManager.GetString("R1_4Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 買不買.
        /// </summary>
        internal static string R1_5 {
            get {
                return ResourceManager.GetString("R1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要買.
        /// </summary>
        internal static string R1_5N {
            get {
                return ResourceManager.GetString("R1_5N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要買.
        /// </summary>
        internal static string R1_5Y {
            get {
                return ResourceManager.GetString("R1_5Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好不好.
        /// </summary>
        internal static string R1_6 {
            get {
                return ResourceManager.GetString("R1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不好.
        /// </summary>
        internal static string R1_6N {
            get {
                return ResourceManager.GetString("R1_6N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好.
        /// </summary>
        internal static string R1_6Y {
            get {
                return ResourceManager.GetString("R1_6Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要不要.
        /// </summary>
        internal static string R1_7 {
            get {
                return ResourceManager.GetString("R1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要.
        /// </summary>
        internal static string R1_7N {
            get {
                return ResourceManager.GetString("R1_7N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要.
        /// </summary>
        internal static string R1_7Y {
            get {
                return ResourceManager.GetString("R1_7Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行不行.
        /// </summary>
        internal static string R1_8 {
            get {
                return ResourceManager.GetString("R1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不行.
        /// </summary>
        internal static string R1_8N {
            get {
                return ResourceManager.GetString("R1_8N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string R1_8Y {
            get {
                return ResourceManager.GetString("R1_8Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇分類.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運勢.
        /// </summary>
        internal static string select_01_1 {
            get {
                return ResourceManager.GetString("select_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 親子.
        /// </summary>
        internal static string select_01_2 {
            get {
                return ResourceManager.GetString("select_01_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 愛情.
        /// </summary>
        internal static string select_01_3 {
            get {
                return ResourceManager.GetString("select_01_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 財富.
        /// </summary>
        internal static string select_01_4 {
            get {
                return ResourceManager.GetString("select_01_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事業.
        /// </summary>
        internal static string select_01_5 {
            get {
                return ResourceManager.GetString("select_01_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 學業.
        /// </summary>
        internal static string select_01_6 {
            get {
                return ResourceManager.GetString("select_01_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string select_01_7 {
            get {
                return ResourceManager.GetString("select_01_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送出.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免費 超準 算命 占卜 財運 事業 工作 爱情 感情 婚姻.
        /// </summary>
        internal static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人和.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南.
        /// </summary>
        internal static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請勾選問題的性質是屬於下列哪一類型.
        /// </summary>
        internal static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 春.
        /// </summary>
        internal static string spring {
            get {
                return ResourceManager.GetString("spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抄兵佈棋.
        /// </summary>
        internal static string Submit1 {
            get {
                return ResourceManager.GetString("Submit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看結果.
        /// </summary>
        internal static string Submit2 {
            get {
                return ResourceManager.GetString("Submit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 困境很久，終於得到暫時的舒解，必須統一資源分配過度.
        /// </summary>
        internal static string Suggest0_0_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有同樣的對手，針對同樣目標在進行競爭，會被對手打敗.
        /// </summary>
        internal static string Suggest0_0_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 執行上得以順利，暫時得到貴人相協助，但防止內部破壞.
        /// </summary>
        internal static string Suggest0_0_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用方法錯誤，導致無法有效掌握事件的運辰，容易誤判事實.
        /// </summary>
        internal static string Suggest0_0_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一切就緒可以行動，但要有不斷的修正方向，維持在一定表準.
        /// </summary>
        internal static string Suggest0_0_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按部就班，小心的經營，會有意想不到的利益或好處和成功.
        /// </summary>
        internal static string Suggest0_0_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將有完全的轉機是良性改變，必須集中資源隨時應變.
        /// </summary>
        internal static string Suggest0_0_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易不自覺的陷入困境，必須將問題根源，找出才能打開困境.
        /// </summary>
        internal static string Suggest0_0_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均對待兩人，共享要持公平原則，相互分工.
        /// </summary>
        internal static string Suggest0_0_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自不量力做出超過能力以外的承擔，就會失敗，要知道何時收場.
        /// </summary>
        internal static string Suggest0_0_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前途艱難，執行上產生困難，意見不和吵架，但目標一致.
        /// </summary>
        internal static string Suggest0_0_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一切以準備完成，已可以行動，而且非動不可，因為情勢一定.
        /// </summary>
        internal static string Suggest0_0_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可急，容易發生不可測狀況，應該照原則規定行事.
        /// </summary>
        internal static string Suggest0_0_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放棄所有的資源，重新開始，容易賠倒所有一切資源.
        /// </summary>
        internal static string Suggest0_0_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若小有成就必須好好培養，不可自滿容易無疾而終.
        /// </summary>
        internal static string Suggest0_0_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 陷入混亂局面到不可解脫情境，最好先思考周詳.
        /// </summary>
        internal static string Suggest0_0_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 強大的企圖，造成行為失去原則，容易鬥爭，大勢將遠去.
        /// </summary>
        internal static string Suggest0_1_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狀況不明所以不可貪，只要掌握得到的就行了，見好就收不可想戀戰.
        /// </summary>
        internal static string Suggest0_1_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看到的只是虛幻只會徒勞無功，不要一昧己見，小心被騙.
        /// </summary>
        internal static string Suggest0_1_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看得到得不到，無奈無法達成目標，必須改變方式.
        /// </summary>
        internal static string Suggest0_1_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前的困難將會一個一個的解脫，但不代表問題會解決.
        /// </summary>
        internal static string Suggest0_1_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一直不段的循環，同一個步驟沒有建樹，重新開始.
        /// </summary>
        internal static string Suggest0_1_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易被設計而步入不可脫身的困境不可雞婆.
        /// </summary>
        internal static string Suggest0_1_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會有爭執或計畫產生矛盾及競爭事件，小心有訴訟危機.
        /// </summary>
        internal static string Suggest0_1_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功是注定的，只是時間的問題，運勢將起，只可惜時限不久.
        /// </summary>
        internal static string Suggest0_1_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沈重的壓力，又逢到抉擇性的問題，但不管如何抉擇，終究是錯.
        /// </summary>
        internal static string Suggest0_1_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要達到目標很難，除非再用功努力，會否極泰來，完成不可能的任務.
        /// </summary>
        internal static string Suggest0_1_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只有等待下一次機會，有些事物是有循環的時機，成熟自然成.
        /// </summary>
        internal static string Suggest0_1_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只要做好準備等待時機，機會自然就會自己來.
        /// </summary>
        internal static string Suggest0_1_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作岸觀火鬥，漁翁得力時，不要隨便和人競爭，只要拾便宜.
        /// </summary>
        internal static string Suggest0_1_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光想不做有計畫不執行，只想一步登天，卻又走不出那一步.
        /// </summary>
        internal static string Suggest0_1_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心將遭遇新的問題，容易被朋友或小人設計是個圈套.
        /// </summary>
        internal static string Suggest0_1_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意見相左，組織內部份派系有革命推反的動力產生必須訂原則.
        /// </summary>
        internal static string Suggest1_0_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 想達到目的，且能得到比別人多的資源及控制權，就必須尋求能人協助.
        /// </summary>
        internal static string Suggest1_0_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會產生混亂，無知困境才枯思沒，必須從開始掌握過程方法.
        /// </summary>
        internal static string Suggest1_0_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 死的不可能活用，盡的不可能再生，必須藉助他人之力，或尋求代用資源.
        /// </summary>
        internal static string Suggest1_0_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會一鳴驚人或打吵驚蛇，應小人的改變，狀況不可急攻進切.
        /// </summary>
        internal static string Suggest1_0_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任人擺佈，拿人手短吃人嘴軟容易被控制.
        /// </summary>
        internal static string Suggest1_0_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 險中求勝，必須要把持自我原則，及可解遭遇的狀況或損失.
        /// </summary>
        internal static string Suggest1_0_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易落入陷阱，最好自然發展，切忌躁進（有牢獄之災）.
        /// </summary>
        internal static string Suggest1_0_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘恩負義，背叛洩密，做小動作，貴人變小人.
        /// </summary>
        internal static string Suggest1_0_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很容易成功而自滿，而且成功一次就沒下一次，所以要不斷的改進，否則自滅.
        /// </summary>
        internal static string Suggest1_0_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將會凸顯但也表示目標明顯，易自滿而遭忌，也該收場的時候.
        /// </summary>
        internal static string Suggest1_0_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要一昧追求表象，而放棄了一切可控制的資源，有被騙的可能.
        /// </summary>
        internal static string Suggest1_0_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將過去舊有的資源再使用，不可一味，追求新方式，容易失敗.
        /// </summary>
        internal static string Suggest1_0_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 順應時事以理性規則去處理，可得天助.
        /// </summary>
        internal static string Suggest1_0_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要協助，而可以得到協助，但是有條件的協助會動搖本來的根本.
        /// </summary>
        internal static string Suggest1_0_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聽天由命請神協助，目前最好集中所有的資源，有效分配.
        /// </summary>
        internal static string Suggest1_0_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要改變原則，會影響整體利益時必須事前溝通以後，再改變規定.
        /// </summary>
        internal static string Suggest1_1_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資源不平均的運用，造成食之無味，棄之可惜，必須統一供同執行功能.
        /// </summary>
        internal static string Suggest1_1_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消滅後再用別的方式重生，可以逃避不必要的困腦，又可存在.
        /// </summary>
        internal static string Suggest1_1_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有點賭運氣的味道，所以容易化為烏有，必須瞭解實情再動作.
        /// </summary>
        internal static string Suggest1_1_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可欺騙，一切都是假象，迷思此一假象，必須解決.
        /// </summary>
        internal static string Suggest1_1_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心賠去所有的資源還得不到預期的目標.
        /// </summary>
        internal static string Suggest1_1_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果順應事實或趁火打劫，小心失敗、最好自律，重新整理資源。.
        /// </summary>
        internal static string Suggest1_1_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曲高和寡必須制訂規劃規則而且少說多做按部就班.
        /// </summary>
        internal static string Suggest1_1_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前處於非常平和的處境，名聲揚名立萬持續發展.
        /// </summary>
        internal static string Suggest1_1_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蓄積資源，展現實力，可以開始行動大展身手，成功在望.
        /// </summary>
        internal static string Suggest1_1_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曾有初步的結果，但是基礎不穩定，必須隨時保持基礎穩定.
        /// </summary>
        internal static string Suggest1_1_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虛幻情境造成，白忙一場，應不斷學習及修正，不致於被表像所欺.
        /// </summary>
        internal static string Suggest1_1_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 會得到預期資源，順勢而為，但不可躁進，必須有效運用和處理.
        /// </summary>
        internal static string Suggest1_1_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 花費很大資源，只為了一個小目的，表示努力不足以控管本體以外的資源.
        /// </summary>
        internal static string Suggest1_1_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心得而復失，會一時興起，造成無法補救的失誤.
        /// </summary>
        internal static string Suggest1_1_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 困境可得到舒解，目前必須分工發展才有機會.
        /// </summary>
        internal static string Suggest1_1_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夏.
        /// </summary>
        internal static string summer {
            get {
                return ResourceManager.GetString("summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身邊.
        /// </summary>
        internal static string Surroundings {
            get {
                return ResourceManager.GetString("Surroundings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要維持「主導權」，只要是按照一切正常的普世價值及規則執行，就會順利。此卦最重要的是「主導權」，也代表領導權及最佳的狀況可以執行所占的事情，但是必須注意領導者的功能是哪些？以及包容的心胸。.
        /// </summary>
        internal static string t1_1 {
            get {
                return ResourceManager.GetString("t1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示所問的事情，先前沒有做好計劃或計劃錯誤。此卦代表企劃失誤或觀念錯誤，就好像想的跟實際的不一樣，最好停止，以待時機再做打算，或重新收集可靠資訊情報再重新規劃。.
        /// </summary>
        internal static string t1_10 {
            get {
                return ResourceManager.GetString("t1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示協調、配合、互動、管理，產生負面的問題，或者是還沒達成一定的組織結構，所以要執行所問的事件，不易或不可執行，以免失敗或受到損失。.
        /// </summary>
        internal static string t1_11 {
            get {
                return ResourceManager.GetString("t1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示企圖心不足，或某些能量不足，例如：資金、人員、信心等。由於不足，往往到頭來是白忙一場。所以建議沒有萬全的準備，勿做心急的動作，以免失敗。.
        /// </summary>
        internal static string t1_12 {
            get {
                return ResourceManager.GetString("t1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表短時間內不適合運作所問的事件，最少再等一個半月看時機再占一次。這個卦有暫時停止呼吸的味道。.
        /// </summary>
        internal static string t1_13 {
            get {
                return ResourceManager.GetString("t1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，會產生阻礙或小人及不合作的人，所以造成需要層層的突破，才能開始運作事情。所以不如先置身事外或等待時機。.
        /// </summary>
        internal static string t1_14 {
            get {
                return ResourceManager.GetString("t1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要恪守計畫及有計畫的從事所占卜的事情。「信任及信用」是很重要的。最好要有法規合約或口頭承諾，不可以脫離普世價值及道德規範。此卦最重要的是「規則」、「規律」、「法律」、「原則」，只要恪守，執行就會順利。.
        /// </summary>
        internal static string t1_2 {
            get {
                return ResourceManager.GetString("t1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要有「近程、中程、遠程」等計劃，尤其是謀略式的處世模式很重要，這表示所占的事件是一件很傷神，操頭腦的事情。所以計劃、企劃、謀略、圖謀是本卦的精神所在。.
        /// </summary>
        internal static string t1_3 {
            get {
                return ResourceManager.GetString("t1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要注重在「管理」，重點在流暢及平衡，尤其是互動協調。此卦最重要的是「管理」得當，則所占事件可運作無誤，所以要懂得「捨與得」之間的平衡及無私的公平，方可順利。.
        /// </summary>
        internal static string t1_4 {
            get {
                return ResourceManager.GetString("t1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要維持「能量」，動能是一切事物的運作力量，所以能量可以分為產生能量的「前使物」件，及能量本體，和後能量持續性。一般企圖慾望、目標等是產生動量的「前使物」件。而機會、時間、金錢、理由等就是能量。只要能掌握源源不斷的能量，此卦成功機會大。.
        /// </summary>
        internal static string t1_5 {
            get {
                return ResourceManager.GetString("t1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要以「時間、空間」來執行所占的事情。時間代表長期的計劃，空間代表各地區的發展。或是長時間的開發擴展地域的面，以維持事情的順利進行。.
        /// </summary>
        internal static string t1_6 {
            get {
                return ResourceManager.GetString("t1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要注重互助、互動、協調，尤其本卦有貴人相助的的現象，不適合自作主張，最好被動或順勢而為，表示所占的事件可行但尚不穩定。.
        /// </summary>
        internal static string t1_7 {
            get {
                return ResourceManager.GetString("t1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表錯誤或專制的主導權及不當的領導，也有可能連普世價值都被自私所破壞，所以造成勾心鬥角的情況發生。建議最好暫停運作。只為一己之私，到頭來是失敗收場。.
        /// </summary>
        internal static string t1_8 {
            get {
                return ResourceManager.GetString("t1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表固執、法律、糾紛、不當的規則與制度，造成錯誤或延遲，使事情不宜運作，最好先協商後再考慮是否可行。不然，一味的執著、紛爭，只會浪費時間。.
        /// </summary>
        internal static string t1_9 {
            get {
                return ResourceManager.GetString("t1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時運不對.
        /// </summary>
        internal static string t4_N {
            get {
                return ResourceManager.GetString("t4_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合得宜.
        /// </summary>
        internal static string t4_Y {
            get {
                return ResourceManager.GetString("t4_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 環境不利.
        /// </summary>
        internal static string t5_N {
            get {
                return ResourceManager.GetString("t5_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 環境配合.
        /// </summary>
        internal static string t5_Y {
            get {
                return ResourceManager.GetString("t5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人事不和.
        /// </summary>
        internal static string t6_N {
            get {
                return ResourceManager.GetString("t6_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合得宜.
        /// </summary>
        internal static string t6_Y {
            get {
                return ResourceManager.GetString("t6_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西.
        /// </summary>
        internal static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冬.
        /// </summary>
        internal static string winter {
            get {
                return ResourceManager.GetString("winter", resourceCulture);
            }
        }
    }
}
