//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Chess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Chess.zh_CN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帅.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 风云棋卦.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秋.
        /// </summary>
        internal static string autumn {
            get {
                return ResourceManager.GetString("autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大贵人.
        /// </summary>
        internal static string Benefactor1 {
            get {
                return ResourceManager.GetString("Benefactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敌人.
        /// </summary>
        internal static string Benefactor10 {
            get {
                return ResourceManager.GetString("Benefactor10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好人.
        /// </summary>
        internal static string Benefactor11 {
            get {
                return ResourceManager.GetString("Benefactor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好人.
        /// </summary>
        internal static string Benefactor12 {
            get {
                return ResourceManager.GetString("Benefactor12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小人.
        /// </summary>
        internal static string Benefactor13 {
            get {
                return ResourceManager.GetString("Benefactor13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小人.
        /// </summary>
        internal static string Benefactor14 {
            get {
                return ResourceManager.GetString("Benefactor14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大贵人.
        /// </summary>
        internal static string Benefactor2 {
            get {
                return ResourceManager.GetString("Benefactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大贵人.
        /// </summary>
        internal static string Benefactor3 {
            get {
                return ResourceManager.GetString("Benefactor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中贵人.
        /// </summary>
        internal static string Benefactor4 {
            get {
                return ResourceManager.GetString("Benefactor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中贵人.
        /// </summary>
        internal static string Benefactor5 {
            get {
                return ResourceManager.GetString("Benefactor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小贵人.
        /// </summary>
        internal static string Benefactor6 {
            get {
                return ResourceManager.GetString("Benefactor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小贵人.
        /// </summary>
        internal static string Benefactor7 {
            get {
                return ResourceManager.GetString("Benefactor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敌人.
        /// </summary>
        internal static string Benefactor8 {
            get {
                return ResourceManager.GetString("Benefactor8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敌人.
        /// </summary>
        internal static string Benefactor9 {
            get {
                return ResourceManager.GetString("Benefactor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系我们.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意见/问题内容.
        /// </summary>
        internal static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车.
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 马.
        /// </summary>
        internal static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 东.
        /// </summary>
        internal static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系邮箱.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地利.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前及未来很长时间才有机会可能发生.
        /// </summary>
        internal static string Event0_0_0 {
            get {
                return ResourceManager.GetString("Event0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待49天后，才会有可能产生机会.
        /// </summary>
        internal static string Event0_0_1 {
            get {
                return ResourceManager.GetString("Event0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要等待49天后才会有可能发生.
        /// </summary>
        internal static string Event0_1_0 {
            get {
                return ResourceManager.GetString("Event0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很久就已经存在的事实.
        /// </summary>
        internal static string Event0_1_1 {
            get {
                return ResourceManager.GetString("Event0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前及未来很长时间才有机会可能发生.
        /// </summary>
        internal static string Event1_0_0 {
            get {
                return ResourceManager.GetString("Event1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49天内将有凸显事件.
        /// </summary>
        internal static string Event1_0_1 {
            get {
                return ResourceManager.GetString("Event1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要在等待49天后，才会有可能产生机会.
        /// </summary>
        internal static string Event1_1_0 {
            get {
                return ResourceManager.GetString("Event1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很早已经是存在的事实.
        /// </summary>
        internal static string Event1_1_1 {
            get {
                return ResourceManager.GetString("Event1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 炮.
        /// </summary>
        internal static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我要卜棋卦.
        /// </summary>
        internal static string Fortune {
            get {
                return ResourceManager.GetString("Fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题.
        /// </summary>
        internal static string FortuneSub1 {
            get {
                return ResourceManager.GetString("FortuneSub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占卜答覆.
        /// </summary>
        internal static string FortuneSub2 {
            get {
                return ResourceManager.GetString("FortuneSub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件表现.
        /// </summary>
        internal static string FortuneSub3 {
            get {
                return ResourceManager.GetString("FortuneSub3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时空人为.
        /// </summary>
        internal static string FortuneSub4 {
            get {
                return ResourceManager.GetString("FortuneSub4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四季吉凶.
        /// </summary>
        internal static string FortuneSub5 {
            get {
                return ResourceManager.GetString("FortuneSub5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四方贵人.
        /// </summary>
        internal static string FortuneSub6 {
            get {
                return ResourceManager.GetString("FortuneSub6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 棋卦内涵.
        /// </summary>
        internal static string FortuneSub7 {
            get {
                return ResourceManager.GetString("FortuneSub7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本卦建言.
        /// </summary>
        internal static string FortuneSub8 {
            get {
                return ResourceManager.GetString("FortuneSub8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉转凶.
        /// </summary>
        internal static string FortuneType1 {
            get {
                return ResourceManager.GetString("FortuneType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶.
        /// </summary>
        internal static string FortuneType10 {
            get {
                return ResourceManager.GetString("FortuneType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中凶.
        /// </summary>
        internal static string FortuneType11 {
            get {
                return ResourceManager.GetString("FortuneType11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中凶.
        /// </summary>
        internal static string FortuneType12 {
            get {
                return ResourceManager.GetString("FortuneType12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小凶.
        /// </summary>
        internal static string FortuneType13 {
            get {
                return ResourceManager.GetString("FortuneType13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小凶.
        /// </summary>
        internal static string FortuneType14 {
            get {
                return ResourceManager.GetString("FortuneType14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉.
        /// </summary>
        internal static string FortuneType2 {
            get {
                return ResourceManager.GetString("FortuneType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大吉.
        /// </summary>
        internal static string FortuneType3 {
            get {
                return ResourceManager.GetString("FortuneType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中吉.
        /// </summary>
        internal static string FortuneType4 {
            get {
                return ResourceManager.GetString("FortuneType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中吉.
        /// </summary>
        internal static string FortuneType5 {
            get {
                return ResourceManager.GetString("FortuneType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小吉.
        /// </summary>
        internal static string FortuneType6 {
            get {
                return ResourceManager.GetString("FortuneType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小吉.
        /// </summary>
        internal static string FortuneType7 {
            get {
                return ResourceManager.GetString("FortuneType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶转吉.
        /// </summary>
        internal static string FortuneType8 {
            get {
                return ResourceManager.GetString("FortuneType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大凶.
        /// </summary>
        internal static string FortuneType9 {
            get {
                return ResourceManager.GetString("FortuneType9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兵.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋占卜沿革.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋是诸葛亮(孔明)利用中国易经的思想及结构理论所创造出来的，当初主要是利用简单的木材，制做出推演战略用的沙盘布阵工具，后来孔明利用易经的一元两仪五行思想创造出现代我们所使用的象棋，当时象棋还有另外一项功能，就是用在问卜战事的吉凶，所以象棋透过一元领导的两仪管事五行的结构，产生了正派及反派两个势力的谋略运用(称为阴阳消长)，左右两组仕相车马炮为辅弼(称为两仪)，再配合东营南营北营西营中坛等五营兵随令战斗(称为五行)，所以全盘32颗棋子是配合中国的三合四象思想所创造出来的，象棋的其中一项功能就是占卜。.
        /// </summary>
        internal static string HistoryContent1 {
            get {
                return ResourceManager.GetString("HistoryContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象棋占卜所得到的解答是准确且直接的，所以占卜者要明白一件事，占卜所提出的问题寻求答案，必须是&quot;吉&quot;或&quot;凶&quot;的两极回答，所以占卜不是算命而是问事，例如：问婚姻(江小明家住深圳市福田区振华路88号目前与王碧云小姐认识交往三年【会不会】结婚)，默想三次后将棋随机放入三角格阵中，就可以完成占卜过程，棋卦将会从三角格阵中的排列组合，运算出所问事件的&quot;会&quot;还是&quot;不会&quot;结婚，也可以从组合中得知事件的基础、时机、环境、人为等相关的互动状况，所以占卜首重有事才占，无事不占的原则，占卜时静性心明默想排棋则会奇准无比。.
        /// </summary>
        internal static string HistoryContent2 {
            get {
                return ResourceManager.GetString("HistoryContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 士.
        /// </summary>
        internal static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 象.
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车.
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 马.
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 炮.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卒.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北.
        /// </summary>
        internal static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (一个问题只能问一次,卜卦的结果才准确喔..).
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请心中默念您想问的事情及或相关人姓名或目的后，请按&quot;抄兵布棋&quot;.
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请将32颗棋子中，任意点选6颗棋子.
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天时.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请摘要写下您的问题.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吉凶.
        /// </summary>
        internal static string R1_1 {
            get {
                return ResourceManager.GetString("R1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凶.
        /// </summary>
        internal static string R1_1N {
            get {
                return ResourceManager.GetString("R1_1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吉.
        /// </summary>
        internal static string R1_1Y {
            get {
                return ResourceManager.GetString("R1_1Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有没有.
        /// </summary>
        internal static string R1_2 {
            get {
                return ResourceManager.GetString("R1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有.
        /// </summary>
        internal static string R1_2N {
            get {
                return ResourceManager.GetString("R1_2N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有.
        /// </summary>
        internal static string R1_2Y {
            get {
                return ResourceManager.GetString("R1_2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可不可.
        /// </summary>
        internal static string R1_3 {
            get {
                return ResourceManager.GetString("R1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可以.
        /// </summary>
        internal static string R1_3N {
            get {
                return ResourceManager.GetString("R1_3N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以.
        /// </summary>
        internal static string R1_3Y {
            get {
                return ResourceManager.GetString("R1_3Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会不会.
        /// </summary>
        internal static string R1_4 {
            get {
                return ResourceManager.GetString("R1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不会.
        /// </summary>
        internal static string R1_4N {
            get {
                return ResourceManager.GetString("R1_4N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会.
        /// </summary>
        internal static string R1_4Y {
            get {
                return ResourceManager.GetString("R1_4Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买不买.
        /// </summary>
        internal static string R1_5 {
            get {
                return ResourceManager.GetString("R1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要买.
        /// </summary>
        internal static string R1_5N {
            get {
                return ResourceManager.GetString("R1_5N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要买.
        /// </summary>
        internal static string R1_5Y {
            get {
                return ResourceManager.GetString("R1_5Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好不好.
        /// </summary>
        internal static string R1_6 {
            get {
                return ResourceManager.GetString("R1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不好.
        /// </summary>
        internal static string R1_6N {
            get {
                return ResourceManager.GetString("R1_6N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好.
        /// </summary>
        internal static string R1_6Y {
            get {
                return ResourceManager.GetString("R1_6Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要不要.
        /// </summary>
        internal static string R1_7 {
            get {
                return ResourceManager.GetString("R1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要.
        /// </summary>
        internal static string R1_7N {
            get {
                return ResourceManager.GetString("R1_7N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要.
        /// </summary>
        internal static string R1_7Y {
            get {
                return ResourceManager.GetString("R1_7Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行不行.
        /// </summary>
        internal static string R1_8 {
            get {
                return ResourceManager.GetString("R1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不行.
        /// </summary>
        internal static string R1_8N {
            get {
                return ResourceManager.GetString("R1_8N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string R1_8Y {
            get {
                return ResourceManager.GetString("R1_8Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择分类.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运势.
        /// </summary>
        internal static string select_01_1 {
            get {
                return ResourceManager.GetString("select_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲子.
        /// </summary>
        internal static string select_01_2 {
            get {
                return ResourceManager.GetString("select_01_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱情.
        /// </summary>
        internal static string select_01_3 {
            get {
                return ResourceManager.GetString("select_01_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 财富.
        /// </summary>
        internal static string select_01_4 {
            get {
                return ResourceManager.GetString("select_01_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事业.
        /// </summary>
        internal static string select_01_5 {
            get {
                return ResourceManager.GetString("select_01_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学业.
        /// </summary>
        internal static string select_01_6 {
            get {
                return ResourceManager.GetString("select_01_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string select_01_7 {
            get {
                return ResourceManager.GetString("select_01_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免费 超准 算命 占卜 财运 事业 工作 爱情 感情 婚姻.
        /// </summary>
        internal static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人和.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南.
        /// </summary>
        internal static string south {
            get {
                return ResourceManager.GetString("south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请勾选问题的性质是属于下列哪一类型.
        /// </summary>
        internal static string Specific {
            get {
                return ResourceManager.GetString("Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 春.
        /// </summary>
        internal static string spring {
            get {
                return ResourceManager.GetString("spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抄兵布棋.
        /// </summary>
        internal static string Submit1 {
            get {
                return ResourceManager.GetString("Submit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看结果.
        /// </summary>
        internal static string Submit2 {
            get {
                return ResourceManager.GetString("Submit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 困境很久，终于得到暂时的舒解，必须统一资源分配过度.
        /// </summary>
        internal static string Suggest0_0_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有同样的对手，针对同样目标在进行竞争，会被对手打败.
        /// </summary>
        internal static string Suggest0_0_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行上得以顺利，暂时得到贵人相协助，但防止内部破坏.
        /// </summary>
        internal static string Suggest0_0_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用方法错误，导致无法有效掌握事件的运辰，容易误判事实.
        /// </summary>
        internal static string Suggest0_0_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一切就绪可以行动，但要有不断的修正方向，维持在一定表准.
        /// </summary>
        internal static string Suggest0_0_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按部就班，小心的经营，会有意想不到的利益或好处和成功.
        /// </summary>
        internal static string Suggest0_0_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将有完全的转机是良性改变，必须集中资源随时应变.
        /// </summary>
        internal static string Suggest0_0_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易不自觉的陷入困境，必须将问题根源，找出才能打开困境.
        /// </summary>
        internal static string Suggest0_0_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均对待两人，共享要持公平原则，相互分工.
        /// </summary>
        internal static string Suggest0_0_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自不量力做出超过能力以外的承担，就会失败，要知道何时收场.
        /// </summary>
        internal static string Suggest0_0_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前途艰难，执行上产生困难，意见不和吵架，但目标一致.
        /// </summary>
        internal static string Suggest0_0_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一切以准备完成，已可以行动，而且非动不可，因为情势一定.
        /// </summary>
        internal static string Suggest0_0_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可急，容易发生不可测状况，应该照原则规定行事.
        /// </summary>
        internal static string Suggest0_0_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放弃所有的资源，重新开始，容易赔倒所有一切资源.
        /// </summary>
        internal static string Suggest0_0_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若小有成就必须好好培养，不可自满容易无疾而终.
        /// </summary>
        internal static string Suggest0_0_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 陷入混乱局面到不可解脱情境，最好先思考周详.
        /// </summary>
        internal static string Suggest0_0_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_0_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强大的企图，造成行为失去原则，容易斗争，大势将远去.
        /// </summary>
        internal static string Suggest0_1_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状况不明所以不可贪，只要掌握得到的就行了，见好就收不可想恋战.
        /// </summary>
        internal static string Suggest0_1_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看到的只是虚幻只会徒劳无功，不要一昧己见，小心被骗.
        /// </summary>
        internal static string Suggest0_1_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看得到得不到，无奈无法达成目标，必须改变方式.
        /// </summary>
        internal static string Suggest0_1_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前的困难将会一个一个的解脱，但不代表问题会解决.
        /// </summary>
        internal static string Suggest0_1_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一直不段的循环，同一个步骤没有建树，重新开始.
        /// </summary>
        internal static string Suggest0_1_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易被设计而步入不可脱身的困境不可鸡婆.
        /// </summary>
        internal static string Suggest0_1_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会有争执或计画产生矛盾及竞争事件，小心有诉讼危机.
        /// </summary>
        internal static string Suggest0_1_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功是注定的，只是时间的问题，运势将起，只可惜时限不久.
        /// </summary>
        internal static string Suggest0_1_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沉重的压力，又逢到抉择性的问题，但不管如何抉择，终究是错.
        /// </summary>
        internal static string Suggest0_1_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要达到目标很难，除非再用功努力，会否极泰来，完成不可能的任务.
        /// </summary>
        internal static string Suggest0_1_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只有等待下一次机会，有些事物是有循环的时机，成熟自然成.
        /// </summary>
        internal static string Suggest0_1_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只要做好准备等待时机，机会自然就会自己来.
        /// </summary>
        internal static string Suggest0_1_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作岸观火斗，渔翁得力时，不要随便和人竞争，只要拾便宜.
        /// </summary>
        internal static string Suggest0_1_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光想不做有计画不执行，只想一步登天，却又走不出那一步.
        /// </summary>
        internal static string Suggest0_1_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心将遭遇新的问题，容易被朋友或小人设计是个圈套.
        /// </summary>
        internal static string Suggest0_1_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest0_1_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意见相左，组织内部份派系有革命推反的动力产生必须订原则.
        /// </summary>
        internal static string Suggest1_0_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 想达到目的，且能得到比别人多的资源及控制权，就必须寻求能人协助.
        /// </summary>
        internal static string Suggest1_0_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会产生混乱，无知困境才枯思没，必须从开始掌握过程方法.
        /// </summary>
        internal static string Suggest1_0_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 死的不可能活用，尽的不可能再生，必须借助他人之力，或寻求代用资源.
        /// </summary>
        internal static string Suggest1_0_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会一鸣惊人或打吵惊蛇，应小人的改变，状况不可急攻进切.
        /// </summary>
        internal static string Suggest1_0_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任人摆布，拿人手短吃人嘴软容易被控制.
        /// </summary>
        internal static string Suggest1_0_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 险中求胜，必须要把持自我原则，及可解遭遇的状况或损失.
        /// </summary>
        internal static string Suggest1_0_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容易落入陷阱，最好自然发展，切忌躁进（有牢狱之灾）.
        /// </summary>
        internal static string Suggest1_0_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘恩负义，背叛泄密，做小动作，贵人变小人.
        /// </summary>
        internal static string Suggest1_0_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 很容易成功而自满，而且成功一次就没下一次，所以要不断的改进，否则自灭.
        /// </summary>
        internal static string Suggest1_0_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将会凸显但也表示目标明显，易自满而遭忌，也该收场的时候.
        /// </summary>
        internal static string Suggest1_0_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要一昧追求表象，而放弃了一切可控制的资源，有被骗的可能.
        /// </summary>
        internal static string Suggest1_0_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将过去旧有的资源再使用，不可一味，追求新方式，容易失败.
        /// </summary>
        internal static string Suggest1_0_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顺应时事以理性规则去处理，可得天助.
        /// </summary>
        internal static string Suggest1_0_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要协助，而可以得到协助，但是有条件的协助会动摇本来的根本.
        /// </summary>
        internal static string Suggest1_0_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 听天由命请神协助，目前最好集中所有的资源，有效分配.
        /// </summary>
        internal static string Suggest1_0_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_0_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要改变原则，会影响整体利益时必须事前沟通以后，再改变规定.
        /// </summary>
        internal static string Suggest1_1_0_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源不平均的运用，造成食之无味，弃之可惜，必须统一供同执行功能.
        /// </summary>
        internal static string Suggest1_1_0_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消灭后再用别的方式重生，可以逃避不必要的困脑，又可存在.
        /// </summary>
        internal static string Suggest1_1_0_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有点赌运气的味道，所以容易化为乌有，必须了解实情再动作.
        /// </summary>
        internal static string Suggest1_1_0_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可欺骗，一切都是假象，迷思此一假象，必须解决.
        /// </summary>
        internal static string Suggest1_1_0_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心赔去所有的资源还得不到预期的目标.
        /// </summary>
        internal static string Suggest1_1_0_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果顺应事实或趁火打劫，小心失败、最好自律，重新整理资源。.
        /// </summary>
        internal static string Suggest1_1_0_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曲高和寡必须制订规划规则而且少说多做按部就班.
        /// </summary>
        internal static string Suggest1_1_0_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_0_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前处于非常平和的处境，名声扬名立万持续发展.
        /// </summary>
        internal static string Suggest1_1_1_0_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蓄积资源，展现实力，可以开始行动大展身手，成功在望.
        /// </summary>
        internal static string Suggest1_1_1_0_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曾有初步的结果，但是基础不稳定，必须随时保持基础稳定.
        /// </summary>
        internal static string Suggest1_1_1_0_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚幻情境造成，白忙一场，应不断学习及修正，不致于被表像所欺.
        /// </summary>
        internal static string Suggest1_1_1_0_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会得到预期资源，顺势而为，但不可躁进，必须有效运用和处理.
        /// </summary>
        internal static string Suggest1_1_1_1_0_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 花费很大资源，只为了一个小目的，表示努力不足以控管本体以外的资源.
        /// </summary>
        internal static string Suggest1_1_1_1_0_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小心得而复失，会一时兴起，造成无法补救的失误.
        /// </summary>
        internal static string Suggest1_1_1_1_1_0 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 困境可得到舒解，目前必须分工发展才有机会.
        /// </summary>
        internal static string Suggest1_1_1_1_1_1 {
            get {
                return ResourceManager.GetString("Suggest1_1_1_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夏.
        /// </summary>
        internal static string summer {
            get {
                return ResourceManager.GetString("summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身边.
        /// </summary>
        internal static string Surroundings {
            get {
                return ResourceManager.GetString("Surroundings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要维持「主导权」，只要是按照一切正常的普世价值及规则执行，就会顺利。此卦最重要的是「主导权」，也代表领导权及最佳的状况可以执行所占的事情，但是必须注意领导者的功能是哪些？以及包容的心胸。.
        /// </summary>
        internal static string t1_1 {
            get {
                return ResourceManager.GetString("t1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示所问的事情，先前没有做好计划或计划错误。此卦代表规划失误或观念错误，就好像想的跟实际的不一样，最好停止，以待时机再做打算，或重新收集可靠信息情报再重新规划。.
        /// </summary>
        internal static string t1_10 {
            get {
                return ResourceManager.GetString("t1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示协调、配合、互动、管理，产生负面的问题，或者是还没达成一定的组织结构，所以要执行所问的事件，不易或不可执行，以免失败或受到损失。.
        /// </summary>
        internal static string t1_11 {
            get {
                return ResourceManager.GetString("t1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，表示企图心不足，或某些能量不足，例如：资金、人员、信心等。由于不足，往往到头来是白忙一场。所以建议没有万全的准备，勿做心急的动作，以免失败。.
        /// </summary>
        internal static string t1_12 {
            get {
                return ResourceManager.GetString("t1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表短时间内不适合运作所问的事件，最少再等一个半月看时机再占一次。这个卦有暂时停止呼吸的味道。.
        /// </summary>
        internal static string t1_13 {
            get {
                return ResourceManager.GetString("t1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，会产生阻碍或小人及不合作的人，所以造成需要层层的突破，才能开始运作事情。所以不如先置身事外或等待时机。.
        /// </summary>
        internal static string t1_14 {
            get {
                return ResourceManager.GetString("t1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要恪守计画及有计画的从事所占卜的事情。 「信任及信用」是很重要的。最好要有法规合约或口头承诺，不可以脱离普世价值及道德规范。此卦最重要的是「规则」、「规律」、「法律」、「原则」，只要恪守，执行就会顺利。.
        /// </summary>
        internal static string t1_2 {
            get {
                return ResourceManager.GetString("t1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要有「近程、中程、远程」等计划，尤其是谋略式的处世模式很重要，这表示所占的事件是一件很伤神，操头脑的事情。所以计划、企划、谋略、图谋是本卦的精神所在。.
        /// </summary>
        internal static string t1_3 {
            get {
                return ResourceManager.GetString("t1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要注重在「管理」，重点在流畅及平衡，尤其是互动协调。此卦最重要的是「管理」得当，则所占事件可运作无误，所以要懂得「舍与得」之间的平衡及无私的公平，方可顺利。.
        /// </summary>
        internal static string t1_4 {
            get {
                return ResourceManager.GetString("t1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要维持「能量」，动能是一切事物的运作力量，所以能量可以分为产生能量的「前使物」件，及能量本体，和后能量持续性。一般企图欲望、目标等是产生动量的「前使物」件。而机会、时间、金钱、理由等就是能量。只要能掌握源源不断的能量，此卦成功机会大。.
        /// </summary>
        internal static string t1_5 {
            get {
                return ResourceManager.GetString("t1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要以「时间、空间」来执行所占的事情。时间代表长期的计划，空间代表各地区的发展。或是长时间的开发扩展地域的面，以维持事情的顺利进行。.
        /// </summary>
        internal static string t1_6 {
            get {
                return ResourceManager.GetString("t1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，要注重互助、互动、协调，尤其本卦有贵人相助的的现象，不适合自作主张，最好被动或顺势而为，表示所占的事件可行但尚不稳定。.
        /// </summary>
        internal static string t1_7 {
            get {
                return ResourceManager.GetString("t1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表错误或专制的主导权及不当的领导，也有可能连普世价值都被自私所破坏，所以造成勾心斗角的情况发生。建议最好暂停运作。只为一己之私，到头来是失败收场。.
        /// </summary>
        internal static string t1_8 {
            get {
                return ResourceManager.GetString("t1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占得此卦，代表固执、法律、纠纷、不当的规则与制度，造成错误或延迟，使事情不宜运作，最好先协商后再考虑是否可行。不然，一味的执着、纷争，只会浪费时间。.
        /// </summary>
        internal static string t1_9 {
            get {
                return ResourceManager.GetString("t1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时运不对.
        /// </summary>
        internal static string t4_N {
            get {
                return ResourceManager.GetString("t4_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合得宜.
        /// </summary>
        internal static string t4_Y {
            get {
                return ResourceManager.GetString("t4_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 环境不利.
        /// </summary>
        internal static string t5_N {
            get {
                return ResourceManager.GetString("t5_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 环境配合.
        /// </summary>
        internal static string t5_Y {
            get {
                return ResourceManager.GetString("t5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人事不和.
        /// </summary>
        internal static string t6_N {
            get {
                return ResourceManager.GetString("t6_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合得宜.
        /// </summary>
        internal static string t6_Y {
            get {
                return ResourceManager.GetString("t6_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称呼.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西.
        /// </summary>
        internal static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冬.
        /// </summary>
        internal static string winter {
            get {
                return ResourceManager.GetString("winter", resourceCulture);
            }
        }
    }
}
